version: "3.8"

services:

  configserver:
    image: abhilashgeorge/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - george
      
  accounts:
    image: abhilashgeorge/accounts:latest
    mem_limit: 700m
    ports:
      - "9090:9090"
    networks:
      - george
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
  
  loans:
    image: abhilashgeorge/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - george
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

      
networks:
  george: